apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
  name: nginx 
spec:
  containers: 
  - name: bear 
    image: supergiantkir/animals:bear 
    volumeMounts:
    - name: app-storage
      mountPath: /storage
  - name: springapp
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: app-storage
      mountPath: /storage
volumes:
  - name: app-storage
    emptyDir: {}
volumeMounts:
 - name: app-storage
   mountPath: /tmp/files

